Repository Seagate/cortx-management-portal, pull requests merged in 2020-10, with the labels that each got.

#149 [cortx-1.0] Resolve empty about page
  gui/src/components/maintenance/cortx-about.vue
Labels: bug

#156 [main] Fixes onboarding on Success msg
  gui/src/components/onboarding/finish.vue
  gui/src/i18n.ts
Labels: bug

#147 [main] Resolve empty about page
  gui/src/components/maintenance/cortx-about.vue
Labels: bug

#161 [cortx 1.0 dev] Eos 14269: Fix translation on update software page
  gui/src/components/maintenance/cortx-software.vue
Labels: bug

#103 [main] Add a script to update the en.json for updating title on run time
  cicd/build.sh
  gui/.env
  gui/public/Cortx-logo-GRN.svg
  gui/public/brand-CORTX.css
  gui/src/App.vue
  gui/src/assets/CORTX-Logo-WHT.svg
  gui/src/assets/Cortx-logo-GRN.svg
  gui/src/i18n.ts
  gui/src/locales/en.json
Labels: enhancement

#101 [main] Add permission for lyve_pilot
  gui/src/common/user-permissions-map.ts
  gui/src/components/navigation/nav-bar.vue
  gui/src/router.ts
Labels: enhancement

#166 Fix incorrect translations
  gui/src/components/onboarding/system-config/data-network/data-network-ipv6.vue
  gui/src/components/onboarding/system-config/data-network/data-network.vue
  gui/src/components/onboarding/system-config/user-settings/user-setting-ldap.vue
Labels: bug

#97 [main] Update en.json with all the text from on-boarding screen
  gui/src/components/onboarding/finish.vue
  gui/src/components/onboarding/homebase.vue
  gui/src/components/onboarding/system-config/appliance-name/appliance-name-config.vue
  gui/src/components/onboarding/system-config/data-network/data-network-ipv4-config.vue
  gui/src/components/onboarding/system-config/data-network/data-network-ipv4.vue
  gui/src/components/onboarding/system-config/data-network/data-network-ipv6.vue
  gui/src/components/onboarding/system-config/data-network/data-network.vue
  gui/src/components/onboarding/system-config/date-time/date-time-config.vue
  gui/src/components/onboarding/system-config/date-time/date-time.vue
  gui/src/components/onboarding/system-config/dns/dns-setting-config.vue
  gui/src/components/onboarding/system-config/dns/dns-setting.vue
  gui/src/components/onboarding/system-config/firmware/firmware.vue
  gui/src/components/onboarding/system-config/interface-select/interface-select.vue
  gui/src/components/onboarding/system-config/mgmt-network/network-settings-ipv4-config.vue
  gui/src/components/onboarding/system-config/mgmt-network/network-settings-ipv4.vue
  gui/src/components/onboarding/system-config/mgmt-network/network-settings-ipv6.vue
  gui/src/components/onboarding/system-config/mgmt-network/network-settings.vue
  gui/src/components/onboarding/system-config/notifications/notifications-email-config.vue
  gui/src/components/onboarding/system-config/notifications/notifications-email.vue
  gui/src/components/onboarding/system-config/notifications/notifications-syslog.vue
  gui/src/components/onboarding/system-config/notifications/notifications.vue
  gui/src/components/onboarding/system-config/ssl-certificate/install-ssl.vue
  gui/src/components/onboarding/system-config/ssl-certificate/upload-ssl-config.vue
  gui/src/components/onboarding/system-config/ssl-certificate/upload-ssl.vue
  gui/src/components/onboarding/system-config/summary/onboarding-summary.vue
  gui/src/components/onboarding/system-config/user-settings/user-setting-ldap.vue
  gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
  gui/src/components/onboarding/system-config/user-settings/user-setting.vue
  gui/src/locales/en.json
Labels: enhancement

#92 [main] Update en.json with all the text from preboarding screen
  gui/src/components/preboarding/admin-user.vue
  gui/src/components/preboarding/license-agreement.vue
  gui/src/components/preboarding/license.vue
  gui/src/components/preboarding/login.vue
  gui/src/components/preboarding/welcome.vue
  gui/src/locales/en.json
Labels: enhancement

#124 [Main] EOS-11603: CSM: Edit comment using patch for Alert command is not working
  web/src/config/client_swagger.json
  web/src/config/swagger.json
Labels: needs-attention

#99 [main] Update en.json with all the missing texts
  gui/src/components/alerts/alert-comments.vue
  gui/src/components/alerts/alert-details.vue
  gui/src/components/alerts/alert-history-details.vue
  gui/src/components/alerts/alert-large.vue
  gui/src/components/alerts/alert-medium.vue
  gui/src/components/alerts/alert-occurrences.vue
  gui/src/components/dashboard/capacity-gauge.vue
  gui/src/components/dashboard/stats/stats-medium.vue
  gui/src/components/header/header-bar.vue
  gui/src/components/health/cortx-health-menu.vue
  gui/src/components/health/cortx-health-view.vue
  gui/src/components/health/cortx-severity-based-health-view.vue
  gui/src/components/maintenance/auditlog.vue
  gui/src/components/maintenance/cortx-node-replacement.vue
  gui/src/components/maintenance/cortx-software.vue
  gui/src/components/navigation/nav-bar.vue
  gui/src/components/performance/performance-large.vue
  gui/src/components/s3/configuration-summary.vue
  gui/src/components/security/403.vue
  gui/src/components/security/404.vue
  gui/src/components/settings/data-network-setting.vue
  gui/src/components/settings/dns-data-setting.vue
  gui/src/components/settings/mgmt-network-setting.vue
  gui/src/components/settings/notifications-email-setting.vue
  gui/src/components/settings/ntp-setting.vue
  gui/src/components/settings/ssl-certificate-setting.vue
  gui/src/components/udx/cortx-udx-details.vue
  gui/src/components/udx/cortx-udx-registration.vue
  gui/src/components/widgets/line-chart.vue
  gui/src/locales/en.json
  gui/vue.config.js
  package-lock.json
Labels: enhancement

#186 Modularize alerts component
  gui/src/components/alerts/alert-comments.vue
  gui/src/components/alerts/alert-details.vue
  gui/src/components/alerts/alert-history-details.vue
  gui/src/components/alerts/alert-large.vue
  gui/src/components/alerts/alert-medium.vue
  gui/src/components/alerts/alert-occurrences.vue
  gui/src/components/alerts/alert.json
  gui/src/components/dashboard/capacity-gauge.vue
  gui/src/components/dashboard/dashboard.vue
  gui/src/components/maintenance/auditlog.vue
  gui/src/components/maintenance/cortx-about.vue
  gui/src/components/maintenance/cortx-resource.vue
  gui/src/components/udx/cortx-udx-registration.vue
  gui/src/locales/en.json
  gui/tslint.json
Labels: enhancement

#188 Modularize Dashboard component
  gui/src/components/dashboard/capacity-gauge.vue
  gui/src/components/dashboard/dashboard.json
  gui/src/components/dashboard/stats/stats-medium.vue
  gui/src/components/header/header-bar.vue
  gui/src/components/health/cortx-health-menu.vue
  gui/src/components/health/cortx-health-view.vue
  gui/src/components/health/cortx-severity-based-health-view.vue
  gui/src/components/performance/performance-large.vue
  gui/src/locales/en.json
Labels: enhancement
